In [29]:
import requests
from bs4 import BeautifulSoup

# URL of the webpage to crawl
url = "https://www.myhora.com/%E0%B8%AB%E0%B8%A7%E0%B8%A2/%E0%B8%AA%E0%B8%96%E0%B8%B4%E0%B8%95%E0%B8%B4%E0%B8%AB%E0%B8%A7%E0%B8%A2-%E0%B8%A2%E0%B9%89%E0%B8%AD%E0%B8%99%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%87-20-%E0%B8%9B%E0%B8%B5.aspx?mode=year-range&value=20"

# Send a GET request to the webpage
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the webpage content
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Find the table with the specified ID
    table = soup.find('table', id='dl_lottery_stats_list')
    list_data = []
    # Check if the table was found
    if table:
        # Extract table headers
        headers = [header.text.strip() for header in table.find_all('th')]
        print("Headers:", headers)
        
        # Extract table rows
        rows = table.find_all('tr')
        
        # Loop through rows and extract data
        for row in rows:
            columns = row.find_all('td')
            data = [column.text.strip() for column in columns]
            if data:  # Skip rows without data
                list_data.append(data)
                print("Row data:", data)
    else:
        print("Table with ID 'dl_lottery_stats_list' not found.")
else:
    print(f"Failed to retrieve the webpage. Status code: {response.status_code}")

Headers: []
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2567 \n 67 \n434503\n03\n503\n89\n 839 975 647 778\n89\n 839 975 647 778']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2567 \n 67 \n518504\n04\n504\n31\n 016 428 426 447\n31\n 016 428 426 447']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2567 \n 67 \n530593\n93\n593\n42\n 194 364 421 734\n42\n 194 364 421 734']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2567 \n 67 \n205690\n90\n690\n60\n 747 885 070 137\n60\n 747 885 070 137']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2567 \n 67 \n980116\n16\n116\n17\n 104 763 634 833\n17\n 104 763 634 833']
Row data: ['16 \n เมษายน \n เม.ย. \n 2567 \n 67 \n943598\n98\n598\n79\n 727 729 154 200\n79\n 727 729 154 200']
Row data: ['1 \n เมษายน \n เม.ย. \n 2567 \n 67 \n803481\n81\n481\n90\n 122 809 559 947\n90\n 122 809 559 947']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2567 \n 67 \n997626\n26\n626\n78\n 509 571 329 794\n78\n 509 571 329 794']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2567 \n 67 \n253603\n03\n603\n79\n 900 975 382 703\n79\n 900 975 382 703']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2567 \n 67 \n941395\n95\n395\n43\n 056 330 375 587\n43\n 056 330 375 587']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2567 \n 67 \n607063\n63\n063\n09\n 454 943 544 591\n09\n 454 943 544 591']
Row data: ['17 \n มกราคม \n ม.ค. \n 2567 \n 67 \n105979\n79\n979\n61\n 429 931 196 635\n61\n 429 931 196 635']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2566 \n 66 \n625544\n44\n544\n89\n 600 648 456 882\n89\n 600 648 456 882']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2566 \n 66 \n356757\n57\n757\n85\n 058 410 584 964\n85\n 058 410 584 964']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2566 \n 66 \n251097\n97\n097\n91\n 055 265 092 280\n91\n 055 265 092 280']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2566 \n 66 \n557990\n90\n990\n14\n 346 412 778 961\n14\n 346 412 778 961']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2566 \n 66 \n743951\n51\n951\n63\n 335 913 019 349\n63\n 335 913 019 349']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2566 \n 66 \n931446\n46\n446\n44\n 167 398 272 970\n44\n 167 398 272 970']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2566 \n 66 \n727202\n02\n202\n66\n 324 355 426 615\n66\n 324 355 426 615']
Row data: ['16 \n กันยายน \n ก.ย. \n 2566 \n 66 \n320812\n12\n812\n46\n 037 699 057 344\n46\n 037 699 057 344']
Row data: ['1 \n กันยายน \n ก.ย. \n 2566 \n 66 \n915478\n78\n478\n91\n 521 596 291 692\n91\n 521 596 291 692']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2566 \n 66 \n471782\n82\n782\n67\n 431 739 737 742\n67\n 431 739 737 742']
Row data: ['31 \n กรกฎาคม \n ก.ค. \n 2566 \n 66 \n260453\n53\n453\n11\n 268 708 387 601\n11\n 268 708 387 601']
Row data: ['16 \n กรกฎาคม \n ก.ค. \n 2566 \n 66 \n169530\n30\n530\n62\n 261 384 066 780\n62\n 261 384 066 780']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2566 \n 66 \n922605\n05\n605\n16\n 281 867 491 947\n16\n 281 867 491 947']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2566 \n 66 \n264872\n72\n872\n30\n 519 628 202 874\n30\n 519 628 202 874']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2566 \n 66 \n125272\n72\n272\n09\n 000 681 386 971\n09\n 000 681 386 971']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2566 \n 66 \n132903\n03\n903\n99\n 678 739 693 731\n99\n 678 739 693 731']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2566 \n 66 \n843019\n19\n019\n65\n 500 780 187 269\n65\n 500 780 187 269']
Row data: ['16 \n เมษายน \n เม.ย. \n 2566 \n 66 \n984906\n06\n906\n71\n 670 678 551 797\n71\n 670 678 551 797']
Row data: ['1 \n เมษายน \n เม.ย. \n 2566 \n 66 \n087907\n07\n907\n99\n 111 914 290 698\n99\n 111 914 290 698']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2566 \n 66 \n025873\n73\n873\n73\n 420 800 355 544\n73\n 420 800 355 544']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2566 \n 66 \n417652\n52\n652\n55\n 577 919 748 984\n55\n 577 919 748 984']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2566 \n 66 \n590417\n17\n417\n80\n 195 664 377 523\n80\n 195 664 377 523']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2566 \n 66 \n297411\n11\n411\n92\n 181 789 101 664\n92\n 181 789 101 664']
Row data: ['17 \n มกราคม \n ม.ค. \n 2566 \n 66 \n812519\n19\n519\n47\n 389 443 564 849\n47\n 389 443 564 849']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2565 \n 65 \n157196\n96\n196\n58\n 007 522 250 425\n58\n 007 522 250 425']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2565 \n 65 \n845093\n93\n093\n14\n 411 912 593 855\n14\n 411 912 593 855']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2565 \n 65 \n375805\n05\n805\n08\n 170 786 409 421\n08\n 170 786 409 421']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2565 \n 65 \n121789\n89\n789\n64\n 532 722 157 973\n64\n 532 722 157 973']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2565 \n 65 \n913106\n06\n106\n70\n 722 839 343 922\n70\n 722 839 343 922']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2565 \n 65 \n613106\n06\n106\n15\n 037 158 606 799\n15\n 037 158 606 799']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2565 \n 65 \n484669\n69\n669\n50\n 206 996 194 278\n50\n 206 996 194 278']
Row data: ['16 \n กันยายน \n ก.ย. \n 2565 \n 65 \n943703\n03\n703\n75\n 540 971 432 631\n75\n 540 971 432 631']
Row data: ['1 \n กันยายน \n ก.ย. \n 2565 \n 65 \n929332\n32\n332\n83\n 298 725 210 604\n83\n 298 725 210 604']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2565 \n 65 \n331583\n83\n583\n42\n 271 300 284 876\n42\n 271 300 284 876']
Row data: ['1 \n สิงหาคม \n ส.ค. \n 2565 \n 65 \n436594\n94\n594\n14\n 266 893 282 447\n14\n 266 893 282 447']
Row data: ['16 \n กรกฎาคม \n ก.ค. \n 2565 \n 65 \n620405\n05\n405\n53\n 159 834 061 279\n53\n 159 834 061 279']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2565 \n 65 \n981417\n17\n417\n61\n 242 287 002 542\n61\n 242 287 002 542']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2565 \n 65 \n361807\n07\n807\n92\n 285 549 106 228\n92\n 285 549 106 228']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2565 \n 65 \n319196\n96\n196\n02\n 679 817 213 652\n02\n 679 817 213 652']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2565 \n 65 \n155012\n12\n012\n06\n 247 736 236 540\n06\n 247 736 236 540']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2565 \n 65 \n658642\n42\n642\n09\n 518 778 041 325\n09\n 518 778 041 325']
Row data: ['16 \n เมษายน \n เม.ย. \n 2565 \n 65 \n395919\n19\n919\n58\n 289 859 413 508\n58\n 289 859 413 508']
Row data: ['1 \n เมษายน \n เม.ย. \n 2565 \n 65 \n970618\n18\n618\n10\n 391 738 578 870\n10\n 391 738 578 870']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2565 \n 65 \n737867\n67\n867\n03\n 349 985 788 989\n03\n 349 985 788 989']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2565 \n 65 \n061905\n05\n905\n07\n 236 834 234 691\n07\n 236 834 234 691']
Row data: ['17 \n กุมภาพันธ์ \n ก.พ. \n 2565 \n 65 \n098597\n97\n597\n57\n 085 644 592 816\n57\n 085 644 592 816']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2565 \n 65 \n944308\n08\n308\n30\n 061 942 485 509\n30\n 061 942 485 509']
Row data: ['17 \n มกราคม \n ม.ค. \n 2565 \n 65 \n880159\n59\n159\n92\n 731 786 119 529\n92\n 731 786 119 529']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2564 \n 64 \n819068\n68\n068\n36\n 591 979 419 547\n36\n 591 979 419 547']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2564 \n 64 \n639235\n35\n235\n83\n 097 629 476 522\n83\n 097 629 476 522']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2564 \n 64 \n077258\n58\n258\n82\n 739 740 401 485\n82\n 739 740 401 485']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2564 \n 64 \n032761\n61\n761\n57\n 471 648 245 844\n57\n 471 648 245 844']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2564 \n 64 \n045037\n37\n037\n95\n 247 458 331 755\n95\n 247 458 331 755']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2564 \n 64 \n386372\n72\n372\n38\n 602 964 295 798\n38\n 602 964 295 798']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2564 \n 64 \n578171\n71\n171\n83\n 285 361 379 449\n83\n 285 361 379 449']
Row data: ['16 \n กันยายน \n ก.ย. \n 2564 \n 64 \n070935\n35\n935\n90\n 609 817 007 379\n90\n 609 817 007 379']
Row data: ['1 \n กันยายน \n ก.ย. \n 2564 \n 64 \n114475\n75\n475\n79\n 278 302 123 458\n79\n 278 302 123 458']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2564 \n 64 \n046750\n50\n750\n23\n 421 666 160 355\n23\n 421 666 160 355']
Row data: ['1 \n สิงหาคม \n ส.ค. \n 2564 \n 64 \n910261\n61\n261\n69\n 103 307 004 785\n69\n 103 307 004 785']
Row data: ['16 \n กรกฎาคม \n ก.ค. \n 2564 \n 64 \n556725\n25\n725\n70\n 058 174 233 927\n70\n 058 174 233 927']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2564 \n 64 \n713517\n17\n517\n29\n 073 794 414 511\n29\n 073 794 414 511']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2564 \n 64 \n691861\n61\n861\n17\n 007 054 447 668\n17\n 007 054 447 668']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2564 \n 64 \n292972\n72\n972\n45\n 193 620 723 978\n45\n 193 620 723 978']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2564 \n 64 \n684579\n79\n579\n14\n 615 843 276 970\n14\n 615 843 276 970']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2564 \n 64 \n501272\n72\n272\n18\n 018 306 129 498\n18\n 018 306 129 498']
Row data: ['16 \n เมษายน \n เม.ย. \n 2564 \n 64 \n100787\n87\n787\n56\n 013 143 264 478\n56\n 013 143 264 478']
Row data: ['1 \n เมษายน \n เม.ย. \n 2564 \n 64 \n472270\n70\n270\n05\n 283 755 393 577\n05\n 283 755 393 577']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2564 \n 64 \n890422\n22\n422\n19\n 036 902 256 396\n19\n 036 902 256 396']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2564 \n 64 \n835538\n38\n538\n73\n 290 838 051 806\n73\n 290 838 051 806']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2564 \n 64 \n424603\n03\n603\n39\n 318 861 057 817\n39\n 318 861 057 817']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2564 \n 64 \n912307\n07\n307\n97\n 248 605 282 651\n97\n 248 605 282 651']
Row data: ['17 \n มกราคม \n ม.ค. \n 2564 \n 64 \n384395\n95\n395\n15\n 367 653 566 878\n15\n 367 653 566 878']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2563 \n 63 \n803628\n28\n628\n19\n 336 804 321 924\n19\n 336 804 321 924']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2563 \n 63 \n201303\n03\n303\n70\n 377 828 072 517\n70\n 377 828 072 517']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2563 \n 63 \n100994\n94\n994\n84\n 093 776 834 984\n84\n 093 776 834 984']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2563 \n 63 \n972661\n61\n661\n46\n 368 741 208 255\n46\n 368 741 208 255']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2563 \n 63 \n506404\n04\n404\n40\n 154 598 062 245\n40\n 154 598 062 245']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2563 \n 63 \n286051\n51\n051\n38\n 189 464 045 980\n38\n 189 464 045 980']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2563 \n 63 \n837893\n93\n893\n59\n 594 757 110 595\n59\n 594 757 110 595']
Row data: ['16 \n กันยายน \n ก.ย. \n 2563 \n 63 \n244083\n83\n083\n57\n 127 220 623 853\n57\n 127 220 623 853']
Row data: ['1 \n กันยายน \n ก.ย. \n 2563 \n 63 \n999997\n97\n997\n98\n 636 725 342 957\n98\n 636 725 342 957']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2563 \n 63 \n945811\n11\n811\n88\n 614 712 364 733\n88\n 614 712 364 733']
Row data: ['1 \n สิงหาคม \n ส.ค. \n 2563 \n 63 \n569391\n91\n391\n92\n 575 931 578 809\n92\n 575 931 578 809']
Row data: ['16 \n กรกฎาคม \n ก.ค. \n 2563 \n 63 \n873286\n86\n286\n53\n 510 533 494 682\n53\n 510 533 494 682']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2563 \n 63 \n347258\n58\n258\n83\n 095 362 094 307\n83\n 095 362 094 307']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2563 \n 63 \n516967\n67\n967\n64\n 876 882 565 625\n64\n 876 882 565 625']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2563 \n 63 \n831567\n67\n567\n24\n 264 489 562 582\n24\n 264 489 562 582']
Row data: ['1 \n เมษายน \n เม.ย. \n 2563 \n 63 \n051095\n95\n095\n22\n 285 430 191 364\n22\n 285 430 191 364']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2563 \n 63 \n503446\n46\n446\n77\n 258 726 404 661\n77\n 258 726 404 661']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2563 \n 63 \n875938\n38\n938\n98\n 294 328 597 780\n98\n 294 328 597 780']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2563 \n 63 \n781403\n03\n403\n94\n 515 952 030 918\n94\n 515 952 030 918']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2563 \n 63 \n589227\n27\n227\n06\n 259 552 375 927\n06\n 259 552 375 927']
Row data: ['17 \n มกราคม \n ม.ค. \n 2563 \n 63 \n491774\n74\n774\n68\n 004 132 379 595\n68\n 004 132 379 595']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2562 \n 62 \n510541\n41\n541\n81\n 116 382 140 250\n81\n 116 382 140 250']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2562 \n 62 \n529924\n24\n924\n97\n 043 138 555 665\n97\n 043 138 555 665']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2562 \n 62 \n453522\n22\n522\n81\n 261 617 013 457\n81\n 261 617 013 457']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2562 \n 62 \n017223\n23\n223\n32\n 164 640 085 194\n32\n 164 640 085 194']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2562 \n 62 \n967375\n75\n375\n79\n 323 806 021 206\n79\n 323 806 021 206']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2562 \n 62 \n812564\n64\n564\n15\n 255 625 132 598\n15\n 255 625 132 598']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2562 \n 62 \n691197\n97\n197\n59\n 392 920 606 797\n59\n 392 920 606 797']
Row data: ['16 \n กันยายน \n ก.ย. \n 2562 \n 62 \n340388\n88\n388\n85\n 733 947 925 939\n85\n 733 947 925 939']
Row data: ['1 \n กันยายน \n ก.ย. \n 2562 \n 62 \n798787\n87\n787\n20\n 210 847 274 439\n20\n 210 847 274 439']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2562 \n 62 \n775476\n76\n476\n89\n 149 912 563 580\n89\n 149 912 563 580']
Row data: ['1 \n สิงหาคม \n ส.ค. \n 2562 \n 62 \n387006\n06\n006\n58\n 135 983 562 795\n58\n 135 983 562 795']
Row data: ['15 \n กรกฎาคม \n ก.ค. \n 2562 \n 62 \n369765\n65\n765\n88\n 355 901 113 556\n88\n 355 901 113 556']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2562 \n 62 \n943647\n47\n647\n86\n 239 864 006 375\n86\n 239 864 006 375']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2562 \n 62 \n174055\n55\n055\n29\n 625 884 127 800\n29\n 625 884 127 800']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2562 \n 62 \n516461\n61\n461\n46\n 589 713 215 560\n46\n 589 713 215 560']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2562 \n 62 \n962526\n26\n526\n71\n 669 949 018 828\n71\n 669 949 018 828']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2562 \n 62 \n061324\n24\n324\n25\n 043 476 374 699\n25\n 043 476 374 699']
Row data: ['16 \n เมษายน \n เม.ย. \n 2562 \n 62 \n570331\n31\n331\n23\n 512 930 966 968\n23\n 512 930 966 968']
Row data: ['1 \n เมษายน \n เม.ย. \n 2562 \n 62 \n109767\n67\n767\n52\n 888 959 403 975\n52\n 888 959 403 975']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2562 \n 62 \n724628\n28\n628\n64\n 148 883 154 877\n64\n 148 883 154 877']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2562 \n 62 \n345650\n50\n650\n65\n 137 999 830 837\n65\n 137 999 830 837']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2562 \n 62 \n074824\n24\n824\n56\n 881 910 612 879\n56\n 881 910 612 879']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2562 \n 62 \n967134\n34\n134\n04\n 643 779 197 948\n04\n 643 779 197 948']
Row data: ['17 \n มกราคม \n ม.ค. \n 2562 \n 62 \n197079\n79\n079\n65\n 206 412 127 660\n65\n 206 412 127 660']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2561 \n 61 \n735867\n67\n867\n02\n 031 913 701 884\n02\n 031 913 701 884']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2561 \n 61 \n356564\n64\n564\n62\n 480 948 297 369\n62\n 480 948 297 369']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2561 \n 61 \n021840\n40\n840\n67\n 045 307 561 988\n67\n 045 307 561 988']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2561 \n 61 \n989903\n03\n903\n16\n 471 930 140 876\n16\n 471 930 140 876']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2561 \n 61 \n149840\n40\n840\n58\n 384 576 046 509\n58\n 384 576 046 509']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2561 \n 61 \n200515\n15\n515\n93\n 186 392 192 212\n93\n 186 392 192 212']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2561 \n 61 \n452643\n43\n643\n99\n 594 726 561 810\n99\n 594 726 561 810']
Row data: ['16 \n กันยายน \n ก.ย. \n 2561 \n 61 \n149760\n60\n760\n79\n 323 539 155 297\n79\n 323 539 155 297']
Row data: ['1 \n กันยายน \n ก.ย. \n 2561 \n 61 \n734510\n10\n510\n26\n 464 512 097 202\n26\n 464 512 097 202']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2561 \n 61 \n586117\n17\n117\n10\n 340 670 591 815\n10\n 340 670 591 815']
Row data: ['1 \n สิงหาคม \n ส.ค. \n 2561 \n 61 \n386602\n02\n602\n78\n 832 903 549 726\n78\n 832 903 549 726']
Row data: ['16 \n กรกฎาคม \n ก.ค. \n 2561 \n 61 \n596324\n24\n324\n27\n 403 530 138 362\n27\n 403 530 138 362']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2561 \n 61 \n963623\n23\n623\n83\n 429 901 210 217\n83\n 429 901 210 217']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2561 \n 61 \n223131\n31\n131\n46\n 432 507 132 868\n46\n 432 507 132 868']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2561 \n 61 \n988117\n17\n117\n95\n 310 553 248 650\n95\n 310 553 248 650']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2561 \n 61 \n075629\n29\n629\n20\n 130 357 047 506\n20\n 130 357 047 506']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2561 \n 61 \n248038\n38\n038\n85\n 527 980 225 602\n85\n 527 980 225 602']
Row data: ['16 \n เมษายน \n เม.ย. \n 2561 \n 61 \n739229\n29\n229\n60\n 273 654 076 526\n60\n 273 654 076 526']
Row data: ['1 \n เมษายน \n เม.ย. \n 2561 \n 61 \n412073\n73\n073\n85\n 131 787 638 924\n85\n 131 787 638 924']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2561 \n 61 \n218559\n59\n559\n82\n 064 720 205 489\n82\n 064 720 205 489']
Row data: ['2 \n มีนาคม \n มี.ค. \n 2561 \n 61 \n759415\n15\n415\n29\n 318 870 589 723\n29\n 318 870 589 723']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2561 \n 61 \n309915\n15\n915\n39\n 007 388 230 748\n39\n 007 388 230 748']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2561 \n 61 \n026853\n53\n853\n31\n 106 947 181 519\n31\n 106 947 181 519']
Row data: ['17 \n มกราคม \n ม.ค. \n 2561 \n 61 \n203823\n23\n823\n50\n 624 799 236 397\n50\n 624 799 236 397']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2560 \n 60 \n911234\n34\n234\n98\n 373 495 504 953\n98\n 373 495 504 953']
Row data: ['16 \n ธันวาคม \n ธ.ค. \n 2560 \n 60 \n955596\n96\n596\n89\n 616 836 290 938\n89\n 616 836 290 938']
Row data: ['1 \n ธันวาคม \n ธ.ค. \n 2560 \n 60 \n451005\n05\n005\n33\n 303 626 257 601\n33\n 303 626 257 601']
Row data: ['16 \n พฤศจิกายน \n พ.ย. \n 2560 \n 60 \n292391\n91\n391\n98\n 831 961 477 628\n98\n 831 961 477 628']
Row data: ['1 \n พฤศจิกายน \n พ.ย. \n 2560 \n 60 \n533726\n26\n726\n85\n 165 425 036 485\n85\n 165 425 036 485']
Row data: ['16 \n ตุลาคม \n ต.ค. \n 2560 \n 60 \n413494\n94\n494\n86\n 180 971 128 287\n86\n 180 971 128 287']
Row data: ['1 \n ตุลาคม \n ต.ค. \n 2560 \n 60 \n880714\n14\n714\n52\n 611 726 462 952\n52\n 611 726 462 952']
Row data: ['16 \n กันยายน \n ก.ย. \n 2560 \n 60 \n170143\n43\n143\n71\n 172 647 340 388\n71\n 172 647 340 388']
Row data: ['1 \n กันยายน \n ก.ย. \n 2560 \n 60 \n143224\n24\n224\n65\n 345 679 195 278\n65\n 345 679 195 278']
Row data: ['16 \n สิงหาคม \n ส.ค. \n 2560 \n 60 \n715431\n31\n431\n37\n 115 302 253 945\n37\n 115 302 253 945']
Row data: ['1 \n สิงหาคม \n ส.ค. \n 2560 \n 60 \n756519\n19\n519\n36\n 061 386 787 989\n36\n 061 386 787 989']
Row data: ['16 \n กรกฎาคม \n ก.ค. \n 2560 \n 60 \n820327\n27\n327\n87\n 584 835 390 823\n87\n 584 835 390 823']
Row data: ['1 \n กรกฎาคม \n ก.ค. \n 2560 \n 60 \n112360\n60\n360\n26\n 226 489 005 688\n26\n 226 489 005 688']
Row data: ['16 \n มิถุนายน \n มิ.ย \n 2560 \n 60 \n943142\n42\n142\n47\n 626 878 373 740\n47\n 626 878 373 740']
Row data: ['1 \n มิถุนายน \n มิ.ย \n 2560 \n 60 \n053630\n30\n630\n61\n 121 218 581 881\n61\n 121 218 581 881']
Row data: ['16 \n พฤษภาคม \n พ.ค. \n 2560 \n 60 \n454891\n91\n891\n53\n 008 396 490 603\n53\n 008 396 490 603']
Row data: ['2 \n พฤษภาคม \n พ.ค. \n 2560 \n 60 \n008656\n56\n656\n35\n 573 949 773 923\n35\n 573 949 773 923']
Row data: ['16 \n เมษายน \n เม.ย. \n 2560 \n 60 \n816729\n29\n729\n40\n 766 973 241 807\n40\n 766 973 241 807']
Row data: ['1 \n เมษายน \n เม.ย. \n 2560 \n 60 \n392785\n85\n785\n80\n 020 057 500 709\n80\n 020 057 500 709']
Row data: ['16 \n มีนาคม \n มี.ค. \n 2560 \n 60 \n273863\n63\n863\n92\n 324 918 694 941\n92\n 324 918 694 941']
Row data: ['1 \n มีนาคม \n มี.ค. \n 2560 \n 60 \n978453\n53\n453\n78\n 450 560 052 577\n78\n 450 560 052 577']
Row data: ['16 \n กุมภาพันธ์ \n ก.พ. \n 2560 \n 60 \n229116\n16\n116\n14\n 128 464 375 953\n14\n 128 464 375 953']
Row data: ['1 \n กุมภาพันธ์ \n ก.พ. \n 2560 \n 60 \n054672\n72\n672\n42\n 066 807 426 628\n42\n 066 807 426 628']
Row data: ['17 \n มกราคม \n ม.ค. \n 2560 \n 60 \n145157\n57\n157\n25\n 511 663 516 836\n25\n 511 663 516 836']
Row data: ['30 \n ธันวาคม \n ธ.ค. \n 2559 \n 59 \n377712\n12\n712\n46\n 304 890 477 769\n46\n 304 890 477 769']

*** MAKE CSV

In [37]:
import pandas as pd

# Example list_data (each item is a row of data)

# Initialize a list to hold the reformatted data
reformatted_data = []

# Loop through the list_data and reformat each row
for row in list_data:
    # Split the row data by \n and strip extra whitespace
    data = [item.strip() for item in row[0].split('\n') if item.strip()]
    
    # Reformat the data
    date = ' '.join(data[1:4])
    first_prize = data[5]
    two_digit_top = data[6]
    three_digit_top = data[7]
    two_digit_bottom = data[8]
    
    # Split three_digit numbers and format them
    three_digit_numbers = data[9].split()
    three_digit_front = ' '.join(three_digit_numbers[:2])
    three_digit_back = ' '.join(three_digit_numbers[2:])
    
    # Append the reformatted row to the data list
    reformatted_data.append([date, first_prize, two_digit_top, three_digit_top, two_digit_bottom, three_digit_front, three_digit_back])

# Create a pandas DataFrame from the reformatted data
df = pd.DataFrame(reformatted_data, columns=['วันที่', 'รางวัลที่ 1', '2 ตัวบน', '3 ตัวบน', '2 ตัวล่าง', '3 ตัวหน้า', '3 ตัวล่าง'])

# Print the DataFrame
print(df)

                 วันที่ รางวัลที่ 1 2 ตัวบน 3 ตัวบน 2 ตัวล่าง 3 ตัวหน้า  \
0     กรกฎาคม ก.ค. 2567      434503      03     503        89   839 975
1    มิถุนายน มิ.ย 2567      518504      04     504        31   016 428
2    มิถุนายน มิ.ย 2567      530593      93     593        42   194 364
3     พฤษภาคม พ.ค. 2567      205690      90     690        60   747 885
4     พฤษภาคม พ.ค. 2567      980116      16     116        17   104 763
..                  ...         ...     ...     ...       ...       ...
475   สิงหาคม ส.ค. 2547      868990      90     990        45   956 811
476   กรกฎาคม ก.ค. 2547      205588      88     588        25   696 726
477   กรกฎาคม ก.ค. 2547      312471      71     471        66   313 598
478  มิถุนายน มิ.ย 2547      208713      13     713        87   414 911
479  มิถุนายน มิ.ย 2547      614144      44     144        72   990 776

    3 ตัวล่าง
0     647 778
1     426 447
2     421 734
3     070 137
4     634 833
..        ...
475   510 377
476   461 154
477   664 261
478   459 986
479   425 992

[480 rows x 7 columns]

In [38]:
df

,วันที่,รางวัลที่ 1,2 ตัวบน,3 ตัวบน,2 ตัวล่าง,3 ตัวหน้า,3 ตัวล่าง
0,กรกฎาคม ก.ค. 2567,434503,03,503,89,839 975,647 778
1,มิถุนายน มิ.ย 2567,518504,04,504,31,016 428,426 447
2,มิถุนายน มิ.ย 2567,530593,93,593,42,194 364,421 734
3,พฤษภาคม พ.ค. 2567,205690,90,690,60,747 885,070 137
4,พฤษภาคม พ.ค. 2567,980116,16,116,17,104 763,634 833
...,...,...,...,...,...,...,...
475,สิงหาคม ส.ค. 2547,868990,90,990,45,956 811,510 377
476,กรกฎาคม ก.ค. 2547,205588,88,588,25,696 726,461 154
477,กรกฎาคม ก.ค. 2547,312471,71,471,66,313 598,664 261
478,มิถุนายน มิ.ย 2547,208713,13,713,87,414 911,459 986
479,มิถุนายน มิ.ย 2547,614144,44,144,72,990 776,425 992

In [ ]:
# # Save the DataFrame to a CSV file if needed
df.to_csv('lottery_stats.csv', index=False, encoding='utf-8-sig')
# Optionally, save to Excel with text format to preserve leading zeros